# Generated by Django 3.1.7 on 2021-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_code',
        ),
        migrations.AddField(
            model_name='branch',
            name='account_number',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='branch',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
