# Generated by Django 3.1.7 on 2021-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210512_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='account_number',
            field=models.IntegerField(default=True),
        ),
    ]
