# Generated by Django 3.1.7 on 2021-05-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20210514_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankStatement',
        ),
    ]
